services:
  openclaw:
    build: plugin
    # Allow the OpenClaw plugin to access the host machine's network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TOOL_CALL_WEBHOOK_URL=http://host.docker.internal:4000
    ####
    ports:
      - "127.0.0.1:18789:18789"
    env_file:
      - plugin/.env
    volumes:
      - openclaw-data:/home/openclaw/.openclaw
  backend:
    build: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  frontend:
    build: frontend
    ports:
      - "5173:5173"

volumes:
  openclaw-data: